"use client";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
export type SeriesPart = { slug: string; title: string; partNumber: number };
export function PartNavigator({ seriesTitle, parts, currentSlug }: { seriesTitle: string; parts: SeriesPart[]; currentSlug: string }) {
  const [open, setOpen] = useState(false); const panel = useRef<HTMLDivElement>(null);
  const currentIndex = parts.findIndex((part) => part.slug === currentSlug); const current = parts[currentIndex]; const next = parts[currentIndex + 1];
  useEffect(() => { if (!open) return; const close = (event: MouseEvent) => { if (!panel.current?.contains(event.target as Node)) setOpen(false); }; const escape = (event: KeyboardEvent) => { if (event.key === "Escape") setOpen(false); }; document.addEventListener("mousedown", close); document.addEventListener("keydown", escape); return () => { document.removeEventListener("mousedown", close); document.removeEventListener("keydown", escape); }; }, [open]);
  return <><div className="part-switcher" ref={panel}><button type="button" onClick={() => setOpen((value) => !value)} aria-expanded={open} aria-controls="part-menu" aria-label={`Choose a part. Currently reading part ${current?.partNumber || 1}`}><span>PART</span><b>{current?.partNumber || 1}</b><i>‹</i></button>{open && <div className="part-menu" id="part-menu"><div className="part-menu-head"><span>Series</span><strong>{seriesTitle}</strong><small>Reading part {current?.partNumber || 1} of {parts.length}</small></div><nav aria-label={`Parts in ${seriesTitle}`}>{parts.map((part) => <Link href={`/story/${part.slug}`} className={part.slug === currentSlug ? "is-current" : ""} aria-current={part.slug === currentSlug ? "page" : undefined} key={part.slug}><b>{part.partNumber}</b><span><small>Part {part.partNumber}</small>{part.title}</span>{part.slug === currentSlug && <i>Reading</i>}</Link>)}</nav></div>}</div>{next && <section className="next-part"><span>Continue the series</span><h2>Ready for Part {next.partNumber}?</h2><p>{next.title}</p><Link href={`/story/${next.slug}`}>Read the next part <b>→</b></Link></section>}</>;
}
