"use client";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
export type SeriesPart = { slug: string; title: string; partNumber: number };
export function PartNavigator({ seriesTitle, parts, currentSlug }: { seriesTitle: string; parts: SeriesPart[]; currentSlug: string }) {
  const [open, setOpen] = useState(false); const panel = useRef<HTMLDivElement>(null);
  const currentIndex = parts.findIndex((part) => part.slug === currentSlug); const current = parts[currentIndex]; const previous = parts[currentIndex - 1]; const next = parts[currentIndex + 1];
  useEffect(() => { if (!open) return; const close = (event: MouseEvent) => { if (!panel.current?.contains(event.target as Node)) setOpen(false); }; const escape = (event: KeyboardEvent) => { if (event.key === "Escape") setOpen(false); }; document.addEventListener("mousedown", close); document.addEventListener("keydown", escape); return () => { document.removeEventListener("mousedown", close); document.removeEventListener("keydown", escape); }; }, [open]);
  return <><div className="part-switcher" ref={panel}><button type="button" onClick={() => setOpen((value) => !value)} aria-expanded={open} aria-controls="part-menu" aria-label={`Choose a part. Currently reading part ${current?.partNumber || 1} of ${parts.length}`}><i className="part-list-icon" aria-hidden="true"><span /><span /><span /></i><b>{currentIndex + 1}/{parts.length}</b></button>{open && <div className="part-menu part-menu--simple" id="part-menu"><nav aria-label={`Parts in ${seriesTitle}`}>{parts.map((part) => <Link href={`/story/${part.slug}`} className={part.slug === currentSlug ? "is-current" : ""} aria-current={part.slug === currentSlug ? "page" : undefined} key={part.slug}><span>Part {part.partNumber}: {part.title}</span></Link>)}</nav></div>}</div><nav className="series-part-nav" aria-label={`Navigate ${seriesTitle}`}><div>{previous ? <Link href={`/story/${previous.slug}`}><span>← Previous part</span><strong>Part {previous.partNumber}: {previous.title}</strong></Link> : <span className="is-disabled" aria-disabled="true"><span>← Previous part</span><strong>This is the first part</strong></span>}</div><div>{next ? <Link href={`/story/${next.slug}`}><span>Next part →</span><strong>Part {next.partNumber}: {next.title}</strong></Link> : <span className="is-disabled" aria-disabled="true"><span>Next part →</span><strong>This is the latest part</strong></span>}</div></nav></>;
}
