"use client";
import { FormEvent, useEffect, useState } from "react";
import { useAdminLocale } from "./AdminLocale";

type User = { id: number; name: string; email: string; active: boolean; createdAt: string };
export function UserManagement() {
  const { t, locale } = useAdminLocale(); const [users, setUsers] = useState<User[]>([]); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  async function load() { const response = await fetch("/api/admin/users"); const result = await response.json() as { users?: User[] }; if (response.ok) setUsers(result.users || []); }
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, []);
  async function add(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setMessage(""); const form = event.currentTarget; const data = Object.fromEntries(new FormData(form)); const response = await fetch("/api/admin/users", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(data) }); const result = await response.json() as { message?: string }; setMessage(response.ok ? t("userAdded") : result.message || t("saveFailed")); if (response.ok) { form.reset(); await load(); } setSaving(false); }
  async function remove(id: number) { if (!confirm(t("deleteUserConfirm"))) return; const response = await fetch(`/api/admin/users?id=${id}`, { method: "DELETE" }); if (response.ok) setUsers((items) => items.filter((user) => user.id !== id)); }
  async function changePassword(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setMessage(""); const form = event.currentTarget; const data = Object.fromEntries(new FormData(form)); const response = await fetch("/api/admin/change-password", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(data) }); const result = await response.json() as { message?: string }; setMessage(response.ok ? t("passwordChanged") : result.message || t("resetFailed")); if (response.ok) form.reset(); setSaving(false); }
  return <main className="admin-main"><div className="admin-page-title"><div><span>{t("system")}</span><h1>{t("users")}</h1><p>{t("usersDescription")}</p></div></div>{message && <div className="admin-notice" role="status">{message}</div>}<div className="admin-user-grid"><form className="admin-panel admin-user-form" onSubmit={add}><h2>{t("addUser")}</h2><label>{t("name")}<input name="name" required maxLength={120} /></label><label>{t("email")}<input name="email" type="email" required maxLength={254} /></label><label>{t("newPassword")}<input name="password" type="password" minLength={8} required autoComplete="new-password" /></label><button className="admin-primary" disabled={saving}>{t("addUser")}</button></form><form className="admin-panel admin-user-form" onSubmit={changePassword}><h2>{t("changePassword")}</h2><label>{t("accountEmailOptional")}<input name="email" type="email" maxLength={254} /></label><label>{t("currentPassword")}<input name="currentPassword" type="password" required autoComplete="current-password" /></label><label>{t("newPassword")}<input name="newPassword" type="password" minLength={8} required autoComplete="new-password" /></label><button className="admin-primary" disabled={saving}>{t("changePassword")}</button></form></div><section className="admin-panel admin-users-list"><h2>{t("userList")}</h2>{users.map((user) => <article key={user.id}><div><b>{user.name}</b><span>{user.email} · {new Date(user.createdAt).toLocaleDateString(locale === "vi" ? "vi-VN" : "en-US")}</span></div><button type="button" className="danger" onClick={() => remove(user.id)}>{t("delete")}</button></article>)}{!users.length && <p>{t("noAdditionalUsers")}</p>}</section></main>;
}
